# In this file are the constants for the BT values
# all values needed for the BT are here

# Collision prevention subtree
COLLISION_MIN_DISTANCE_CM = 10  # THIS ONE DOES NOT GO HERE
COLLISION_BACK_OFF_TIME_SECONDS = 3
COLLISION_BACK_OFF_SPEED = 50
COLLISION_SPIN_TIME_SECONDS = 3
COLLISION_SPIN_SPEED = 50

STUCK_BACK_OFF_TIME_SECONDS = 1
STUCK_BACK_OFF_SPEED = 50
STUCK_ADVANCE_TIME_SECONDS = 1
STUCK_ADVANCE_SPEED = 50
STUCK_SPIN_TIME_SECONDS = 3  # unused
STUCK_SPIN_SPEED = 50  # unused
