TF_MODEL = "limpiaplayas2022v3.tflite"
CAMERA_ID = 0
CAMERA_WIDTH_MOCK = 640
CAMERA_HEIGHT_MOCK = 480
CAMERA_WIDTH_RASPBERRY = 120
CAMERA_HEIGHT_RASPBERRY = 160
NUMBER_THREADS = 4
ENABLE_EDGETPU = False
