ARM_PINS = (0, 1)
CLAW_PINS = (4, 5)
TRAY_PINS = (2, 3)

ARM_EXPANDED_DEGREES = 150
ARM_RETRACTED_DEGREES = 20

CLAW_EXPANDED_DEGREES = 0
CLAW_RETRACTED_DEGREES = 60

TRAY_EXPANDED_DEGREES = 45
TRAY_RETRACTED_DEGREES = 3

PCA9685_FREQUENCY = 50
