ARM_PINS = (0, 1)
CLAW_PINS = (2, 3)
TRAY_PINS = (4, 5)

ARM_EXPANDED_DEGREES = 135
ARM_RETRACTED_DEGREES = 15

CLAW_EXPANDED_DEGREES = 45
CLAW_RETRACTED_DEGREES = 0

TRAY_EXPANDED_DEGREES = 30
TRAY_RETRACTED_DEGREES = 0

PCA9685_FREQUENCY = 50
